"""Datos de referencia de constructoras (Cortes y Sistemas - Dic 2024).
Generado automaticamente desde Excel original."""

# Fuente: TOTAL-BLVD CYS - COMPLETO_19-12-24_100%.xlsx
# Constructora: Cortes y Sistemas
# Fecha: Diciembre 2024
# Proyecto: Cabildo Boulevard

DATOS_CONSTRUCTORAS = [
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.01',
        'descripcion': 'Cumpliento de las Disposiciones de Seguridad e Higiene durante transcurso de la Obra según PCG y PET',
        'unidad': 'gl',
        'precio_unitario': 20305535.46,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.02',
        'descripcion': 'Personal de Supervisión, Jefatura de Obra, Representante Técnico',
        'unidad': 'gl',
        'precio_unitario': 106306327.18,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.03',
        'descripcion': 'Control de Accesos a la Obra - Seguridad de obra',
        'unidad': 'gl',
        'precio_unitario': 44285760.21,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.04',
        'descripcion': 'Replanteos y verificacion de medidas y niveles',
        'unidad': 'gl',
        'precio_unitario': 27031226.6,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.06',
        'descripcion': 'Ayuda de Gremios según PLIEGO',
        'unidad': 'gl',
        'precio_unitario': 44977725.22,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.07',
        'descripcion': 'Obradores y equipamiento para Constructora, DO y Personal Tecnico Comitente.  Instalacion de Vestuarios, baño, Comedor y Depositos de Obrador y oficina equipada para D.O. y Comitente.',
        'unidad': 'gl',
        'precio_unitario': 27328487.44,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.08',
        'descripcion': 'Instalacion de baño de Obrador',
        'unidad': 'gl',
        'precio_unitario': 11385819.98,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.09',
        'descripcion': 'Cerco de obra (solo mantenimiento) y Cartel de obra (provisión e instalación). Iluminacion de Cerco y Cartel',
        'unidad': 'gl',
        'precio_unitario': 1924068.19,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.10',
        'descripcion': 'Protecciones y defensas en altura',
        'unidad': 'gl',
        'precio_unitario': 89236929.97,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.11',
        'descripcion': 'Traslado de Equipos, Maquinarias y Enseres y volquetes',
        'unidad': 'gl',
        'precio_unitario': 9187007.0,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.13',
        'descripcion': 'Mantenimiento de muros divisorios',
        'unidad': 'gl',
        'precio_unitario': 6612110.03,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.14',
        'descripcion': 'Instalacion fuerza motriz e iluminacion provisoria para Obrador y ayuda de Gremios (tramitaciones, Instalaciones provisorias y tarifas consumo)',
        'unidad': 'gl',
        'precio_unitario': 19687054.21,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.15',
        'descripcion': 'Pago suministro eléctrico durante el cumplimiento del Contrato\nTableros Electricos provisorios y secundarios durante la Obra',
        'unidad': 'gl',
        'precio_unitario': 12395565.98,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.16',
        'descripcion': 'Instalación Provisoria  y pago consumo de Agua de Obra durante el cumplimiento del Contrato.  infraestructura temporaria de cloacas',
        'unidad': 'gl',
        'precio_unitario': 10973420.83,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.17',
        'descripcion': 'Instalación de Internet durante el cumplimiento del Contrato',
        'unidad': 'gl',
        'precio_unitario': 1490249.15,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.18',
        'descripcion': 'Ocupación  y mantenimiento  de veredas , tramitacion de permisos de cortes de calle y bomba de h° a contramano, permisos de volcamiento de agua de napas. (pago derechos y gestión ante organismos correspondientes)',
        'unidad': 'gl',
        'precio_unitario': 24438721.14,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.19',
        'descripcion': 'Medios de elevación:  Montacargas necesarios para materiales y personas. Transporte vertical y horizontal provision, instalacionm mantenimiento y habilitaciones necesarias ante GCBA  (incluido operador)',
        'unidad': 'gl',
        'precio_unitario': 52144225.75,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.20',
        'descripcion': 'GRUA (si la hubiere): Provisión, operación y mantenimieno, incl.  Gestion y Habilitación municipal',
        'unidad': 'gl',
        'precio_unitario': 116711766.48,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.21',
        'descripcion': 'Limpieza  durante la ejecución de la obra',
        'unidad': 'gl',
        'precio_unitario': 43681663.78,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.22',
        'descripcion': 'Limpieza final para la entrega unidades funcionales',
        'unidad': 'gl',
        'precio_unitario': 7708528.9,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.23',
        'descripcion': 'Limpieza final para la entrega áreas comunes según PET Alb y Afines / Particulares',
        'unidad': 'gl',
        'precio_unitario': 5781396.68,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.24',
        'descripcion': 'Destapación y limpieza final de cañerías',
        'unidad': 'gl',
        'precio_unitario': 1445349.17,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.25',
        'descripcion': 'Tramitaciones Varias ante Organismos de Control',
        'unidad': 'gl',
        'precio_unitario': 15926178.65,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.26',
        'descripcion': 'Confección Planos previos a INICIO de OBRA de estructuras de H°A°, de replanteo de Arquitectura, incluye APTO CONSTRUCCION presentación, gestión,  firma  y aprobación  como Ejecutor Estructural y Constructor ante organismos pertinentes.',
        'unidad': 'gl',
        'precio_unitario': 55972280.27,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.27',
        'descripcion': 'Confección Planos CONFORME a OBRA de estructuras H°A°, de replanteo de Arquitectura:   presentación, gestión,  firma  y aprobación  como Ejecutor Estructural y Constructor ante el organismos pertinentes',
        'unidad': 'gl',
        'precio_unitario': 16791684.08,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.28',
        'descripcion': 'Documentación Complementaria Ejecutiva',
        'unidad': 'gl',
        'precio_unitario': 2854586.29,
        'etapa_nombre': 'Preliminares y Obrador',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '2.01',
        'descripcion': 'Sereno',
        'unidad': 'gl',
        'precio_unitario': 28008107.28,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '2.02',
        'descripcion': 'Vigilancia diurna y control de accesos (por empresa especializada) con camaras segun PET Alb y Afines / Particulares',
        'unidad': 'gl',
        'precio_unitario': 61288328.87,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '2.03',
        'descripcion': 'Grupo Electrogeno (Gastos de habilitacion y mantenimiento) para uso durante la obra.',
        'unidad': 'gl',
        'precio_unitario': 11644111.27,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'organizacion',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.01',
        'descripcion': 'Instalacion de pozos, bombas, canalizaciones e instalacion eléctrica segun pliego',
        'unidad': 'gl',
        'precio_unitario': 40895549.95,
        'etapa_nombre': 'Depresión de Napa / Bombeo',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.02',
        'descripcion': 'Operación y Mantenimiento de la instalacion durante la ejecución de la estructura hasta el cumplimiento del Contrato',
        'unidad': 'gl',
        'precio_unitario': 21766986.26,
        'etapa_nombre': 'Depresión de Napa / Bombeo',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.03',
        'descripcion': 'Provisión de energia eléctrica por grupo electrógeno para la operación del bombeo de depresion de napa durante la ejecución de la estructura en ocasión de cortes de provisión de la Empresa Proveedora. Operación y mantenimiento hasta el cumplimiento del Contrato',
        'unidad': 'gl',
        'precio_unitario': 11661827.79,
        'etapa_nombre': 'Depresión de Napa / Bombeo',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.04',
        'descripcion': 'Cotización de los rubros 1.02 y 1.03 por mes adicional con posterioridad del cumplimiento del contrato',
        'unidad': 'unidades',
        'precio_unitario': 1159791.24,
        'etapa_nombre': 'Depresión de Napa / Bombeo',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.05',
        'descripcion': 'Instalación de bombeo definitivo segun pliego',
        'unidad': 'gl',
        'precio_unitario': 12268664.99,
        'etapa_nombre': 'Depresión de Napa / Bombeo',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.06',
        'descripcion': 'Red depresora de napa- Retiro y cegado de perforaciones',
        'unidad': 'gl',
        'precio_unitario': 6134332.49,
        'etapa_nombre': 'Depresión de Napa / Bombeo',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '2.03',
        'descripcion': 'Cortes de canaletas en medianeras de mampostería',
        'unidad': 'ml',
        'precio_unitario': 42490.92,
        'etapa_nombre': 'Demoliciones',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '2.04',
        'descripcion': 'Picado de revoques excedentes en muros medianeros',
        'unidad': 'gl',
        'precio_unitario': 1897059.83,
        'etapa_nombre': 'Demoliciones',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.04',
        'descripcion': 'Perfilado manual',
        'unidad': 'm2',
        'precio_unitario': 8790.28,
        'etapa_nombre': 'Movimiento de Suelos',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.05',
        'descripcion': 'Excavación de platea',
        'unidad': 'm3',
        'precio_unitario': 12022.34,
        'etapa_nombre': 'Movimiento de Suelos',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.06',
        'descripcion': 'Excavación de zapatas',
        'unidad': 'm3',
        'precio_unitario': 12022.34,
        'etapa_nombre': 'Movimiento de Suelos',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.07',
        'descripcion': 'Excavación de bases y pozos',
        'unidad': 'm3',
        'precio_unitario': 12022.34,
        'etapa_nombre': 'Movimiento de Suelos',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.09',
        'descripcion': 'Excavación General',
        'unidad': 'm3',
        'precio_unitario': 12331.87,
        'etapa_nombre': 'Movimiento de Suelos',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.11',
        'descripcion': 'Relleno con tierra compactada (Valor de referencia)',
        'unidad': 'm3',
        'precio_unitario': 8675.39,
        'etapa_nombre': 'Movimiento de Suelos',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.12',
        'descripcion': 'Agregado: Excavación Hormigón de Limpieza bajo Platea',
        'unidad': 'm3',
        'precio_unitario': 12331.87,
        'etapa_nombre': 'Movimiento de Suelos',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,01,01',
        'descripcion': 'Tabiques de submuración y empuje (Se incluyen columnas en tabiques submurales)',
        'unidad': 'm3',
        'precio_unitario': 1156885.78,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,01,03',
        'descripcion': 'Pilotes de traccion IRS o IGU armado e inyectado, según listado esfuerzo y medidas.',
        'unidad': 'gl',
        'precio_unitario': 351282146.0,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,01,05',
        'descripcion': 'Zapatas tabiques submurales',
        'unidad': 'm3',
        'precio_unitario': 410074.14,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,01,06',
        'descripcion': 'Platea',
        'unidad': 'm3',
        'precio_unitario': 516237.42,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,01,09',
        'descripcion': 'Bajo recorrido ascensores',
        'unidad': 'm3',
        'precio_unitario': 813362.97,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,02,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,02,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,02,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,02,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,02,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,03,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,03,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,03,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,03,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,03,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,03,06',
        'descripcion': 'Rampa vehicular',
        'unidad': 'm3',
        'precio_unitario': 801550.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,04,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,04,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,04,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,04,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,04,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,04,06',
        'descripcion': 'Rampa vehicular',
        'unidad': 'm3',
        'precio_unitario': 801550.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,05,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,05,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,05,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,05,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,05,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,05,06',
        'descripcion': 'Rampa vehicular',
        'unidad': 'm3',
        'precio_unitario': 801550.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,06,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,06,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,06,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,06,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,06,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,06,06',
        'descripcion': 'Rampa vehicular',
        'unidad': 'm3',
        'precio_unitario': 801550.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,07,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,07,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,07,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,07,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,07,06',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,08,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,08,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,08,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,08,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,08,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,09,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,09,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,09,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,09,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,09,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,10,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,10,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,10,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,10,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,10,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,11,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,11,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,11,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,11,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,11,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,12,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,12,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,12,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,12,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,12,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,13,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,13,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,13,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,13,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,13,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,14,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,14,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,14,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,14,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,14,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,15,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,15,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,15,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,15,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,15,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,16,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,16,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,16,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,16,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,16,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,17,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,17,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,17,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,17,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,17,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,18,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,18,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,18,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,18,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,18,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,19,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,19,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,19,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,19,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,19,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,20,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,20,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,20,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,20,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,20,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,21,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,21,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,21,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,21,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,21,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,22,01',
        'descripcion': 'Columnas',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,22,02',
        'descripcion': 'Vigas',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,22,03',
        'descripcion': 'Tabiques',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,22,04',
        'descripcion': 'Losas',
        'unidad': 'm3',
        'precio_unitario': 702938.36,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,22,05',
        'descripcion': 'Escaleras',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,23,01',
        'descripcion': 'Losa',
        'unidad': 'm3',
        'precio_unitario': 721036.38,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,24,01',
        'descripcion': 'Agregado: Columnas 16º Piso',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,24,02',
        'descripcion': 'Agregado: Vigas s/16',
        'unidad': 'm3',
        'precio_unitario': 800513.52,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,24,01',
        'descripcion': 'Agregado: Tabiques 16º Piso',
        'unidad': 'm3',
        'precio_unitario': 878882.22,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,24,02',
        'descripcion': 'Agregado: Escaleras 16º Piso',
        'unidad': 'm3',
        'precio_unitario': 953360.15,
        'etapa_nombre': 'Estructura',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '6,01',
        'descripcion': 'Tanque de incendio',
        'unidad': 'm3',
        'precio_unitario': 810983.25,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '6,02',
        'descripcion': 'Tanque de reserva',
        'unidad': 'm3',
        'precio_unitario': 778914.76,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '6,03',
        'descripcion': 'Tanque de ralentización',
        'unidad': 'm3',
        'precio_unitario': 774122.88,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '6,04',
        'descripcion': 'Provisión  y ejecución de pozos de bombeo y  tanques  complementarios de instalaciones',
        'unidad': 'm3',
        'precio_unitario': 790721.55,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '6,05',
        'descripcion': 'Piscina en planta azotea (gunitado)',
        'unidad': 'm3',
        'precio_unitario': 750327.07,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '6,06',
        'descripcion': 'Hormigón de limpieza bajo platea',
        'unidad': 'm3',
        'precio_unitario': 261780.28,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '6,07',
        'descripcion': 'Ensayos de hormigon',
        'unidad': 'gl',
        'precio_unitario': 25792377.19,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '6,08',
        'descripcion': 'Polietileno 200 micrones entre terreno natural y estructura (tabiques submurales)',
        'unidad': 'm2',
        'precio_unitario': 6457.92,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '6,09',
        'descripcion': 'Colocación de insertos metálicos previstos en hormigon (para silletero azotea, etc )',
        'unidad': 'gl',
        'precio_unitario': 991817.74,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'hormigon_armado',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.01',
        'descripcion': 'MA1 - Ladrillo Ceramico 0,08',
        'unidad': 'm2',
        'precio_unitario': 20264.86,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.02',
        'descripcion': 'MA2 - Ladrillo Ceramico 0,08',
        'unidad': 'm2',
        'precio_unitario': 20264.86,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.03',
        'descripcion': 'MA3- Ladrillo Ceramico 0,08',
        'unidad': 'm2',
        'precio_unitario': 20264.86,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.04',
        'descripcion': 'MA4- Ladrillo Ceramico 0,08',
        'unidad': 'm2',
        'precio_unitario': 20264.86,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.05',
        'descripcion': 'MA5 - Ladrillo Ceramico 0,08',
        'unidad': 'm2',
        'precio_unitario': 20264.86,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.06',
        'descripcion': 'MA6- Ladrillo Ceramico 0,08',
        'unidad': 'm2',
        'precio_unitario': 20264.86,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.09',
        'descripcion': 'MA7- Ladrillo Cerámico 0,04',
        'unidad': 'm2',
        'precio_unitario': 13726.61,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.1',
        'descripcion': 'MA8-  Ladrillo Cerámico 0,04',
        'unidad': 'm2',
        'precio_unitario': 13726.61,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.11',
        'descripcion': 'MB13-Ladrillo Cerámico 0,04',
        'unidad': 'm2',
        'precio_unitario': 13726.61,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.12',
        'descripcion': 'MA9 - Ladrillo Cerámico 0,12',
        'unidad': 'm2',
        'precio_unitario': 28560.79,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.13',
        'descripcion': 'MA10- Ladrillo Cerámico 0,12',
        'unidad': 'm2',
        'precio_unitario': 28560.79,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.14',
        'descripcion': 'MA11- Ladrillo Cerámico 0,12',
        'unidad': 'm2',
        'precio_unitario': 28560.79,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.15',
        'descripcion': 'MA14- Ladrillo Cerámico 0,12',
        'unidad': 'm2',
        'precio_unitario': 28560.79,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.16',
        'descripcion': 'MA12- Ladrillo Cerámico 0,18',
        'unidad': 'm2',
        'precio_unitario': 37932.64,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.17',
        'descripcion': 'MA13- Ladrillo Cerámico 0,18',
        'unidad': 'm2',
        'precio_unitario': 37932.64,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.18',
        'descripcion': 'MC1- Ladrillo Común',
        'unidad': 'm2',
        'precio_unitario': 34486.89,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.19',
        'descripcion': 'MC2- Ladrillo Común',
        'unidad': 'm2',
        'precio_unitario': 34486.89,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.22',
        'descripcion': 'MC5- Ladrillo Común',
        'unidad': 'm2',
        'precio_unitario': 34486.89,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.24',
        'descripcion': 'MC7- Ladrillo Común',
        'unidad': 'm2',
        'precio_unitario': 34486.89,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.25',
        'descripcion': 'MC8- Ladrillo Común',
        'unidad': 'm2',
        'precio_unitario': 34486.89,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.26',
        'descripcion': 'MF1- Bloque HCCA',
        'unidad': 'm2',
        'precio_unitario': 45477.43,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '1.29',
        'descripcion': 'MV1 . L° Vidrio',
        'unidad': 'm2',
        'precio_unitario': 166694.7,
        'etapa_nombre': 'Mampostería',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '2.01',
        'descripcion': 'M14 (Agregado en CIRC Nº 2)',
        'unidad': 'm2',
        'precio_unitario': 24991.24,
        'etapa_nombre': 'Construcción en Seco',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.01',
        'descripcion': 'Tratamiento especial sobre platea o losa de supresion  con capa de adherencia s/PET',
        'unidad': 'm2',
        'precio_unitario': 14250.68,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.02',
        'descripcion': 'Tratamiento especial  sobre tabiques de hormigón en  Subsuelos, h: total, con capa de adherencia s/PET (Se tomó en cuenta H= total para tabiques perimetrales y H= 1,20 M para tabiques y columnas no perimetrales)',
        'unidad': 'm2',
        'precio_unitario': 20246.31,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.03',
        'descripcion': 'Tratamiento especial hidrorepelente para hormigón visto en cielorrasos de fachada (Se tomaron en cuenta cielorrasos en balcones)',
        'unidad': 'm2',
        'precio_unitario': 11833.0,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.04',
        'descripcion': 'Aislación sobre losa de Planta Baja y en áreas de canteros (Se tomó en cuenta Patio y Cantero en PB según Planilla de Locales)',
        'unidad': 'm2',
        'precio_unitario': 33762.49,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.06',
        'descripcion': 'Aislación de veredas en los sectores de retiro de fachada',
        'unidad': 'm2',
        'precio_unitario': 5413.47,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.07',
        'descripcion': 'Aislación hidrófuga muros en contacto con el exterior',
        'unidad': 'm2',
        'precio_unitario': 5413.47,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.08',
        'descripcion': 'Aislación hidrofuga en balcones, en sectores semicubiertos, descubiertos y en cubiertas según PET',
        'unidad': 'm2',
        'precio_unitario': 18334.71,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.09',
        'descripcion': 'Aislación bajo revestimientos y solados en locales sanitarios  S/PET (Azotado hidrofugo horizontal y vertical) Superficie y altura completa de cada local.  S/PET .Barrera de vapor.',
        'unidad': 'm2',
        'precio_unitario': 9956.35,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.10',
        'descripcion': 'Aislación hidrófuga cementicia según PET (Se tomaron en cuenta locales sanitarios, cocinas, office y lavanderia en SS)',
        'unidad': 'm2',
        'precio_unitario': 13675.62,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.11',
        'descripcion': 'Aislac reforzada perimetral bajo bañeras y/o Jacuzzis, c/ ais. Cementicia Según PET',
        'unidad': 'm2',
        'precio_unitario': 31109.08,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.12',
        'descripcion': 'Tratamiento especial para tanques según PET',
        'unidad': 'm2',
        'precio_unitario': 20872.49,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.13',
        'descripcion': 'Tratamiento de juntas en encuentro entre tabiques y pisos en subsuelo',
        'unidad': 'ml',
        'precio_unitario': 26328.38,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.14',
        'descripcion': 'Impermeabilizacion de pozos de bombeos y cámaras',
        'unidad': 'm2',
        'precio_unitario': 20246.31,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.15',
        'descripcion': 'Sellado de fisuras, taponados de nidos de abeja, oquedades, etc.',
        'unidad': 'm2',
        'precio_unitario': 26328.38,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.16',
        'descripcion': 'Barrera de vapor vertical de muros exteriores',
        'unidad': 'm2',
        'precio_unitario': 4779.61,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.18',
        'descripcion': 'Babetas perimetrales',
        'unidad': 'ml',
        'precio_unitario': 3666.94,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.19',
        'descripcion': 'Aislación térmica en techados: poliestireno expandido 5cm (mínimo)  de 20 a 25 kg/m3 de densidad. Barrera de vapor',
        'unidad': 'm2',
        'precio_unitario': 20525.7,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.20',
        'descripcion': 'Aislación acústica según Planilla de Locales',
        'unidad': 'm2',
        'precio_unitario': 12419.62,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.21',
        'descripcion': 'Cajón Hidrófugo (Se tomaron en cuenta mamposterías de 5º y 4º SS según Planilla de Locales)',
        'unidad': 'm2',
        'precio_unitario': 5413.47,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '3.22',
        'descripcion': 'Terraza verde',
        'unidad': 'm2',
        'precio_unitario': 54980.01,
        'etapa_nombre': 'Impermeabilizaciones y Aislaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '4.01',
        'descripcion': 'Ventilación natural en paliers',
        'unidad': 'gl',
        'precio_unitario': 6846713.46,
        'etapa_nombre': 'Ventilaciones y Conductos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '4.02',
        'descripcion': 'Ventilación natural en locales sanitarios (sombrerete de chapa)',
        'unidad': 'gl',
        'precio_unitario': 20507276.16,
        'etapa_nombre': 'Ventilaciones y Conductos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '4.03',
        'descripcion': 'Ventilaciones mecánicas  auxiliares (subsuelos, etc.) Ay. de Gr',
        'unidad': 'gl',
        'precio_unitario': 4108028.08,
        'etapa_nombre': 'Ventilaciones y Conductos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '4.05',
        'descripcion': 'Remates sombreretes reglamentarios (tachos y albañileria)',
        'unidad': 'gl',
        'precio_unitario': 6443965.61,
        'etapa_nombre': 'Ventilaciones y Conductos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,02',
        'descripcion': 'Emprolijado de hormigón visto (CIRC Nº 4)',
        'unidad': 'm2',
        'precio_unitario': 10839.77,
        'etapa_nombre': 'Revoque Grueso',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,03',
        'descripcion': 'Columnas, Muros y mampostería perimetral en subsuelos: jaharro y enlucido a la cal reforzado term. al fieltro h:1,20m',
        'unidad': 'm2',
        'precio_unitario': 17537.85,
        'etapa_nombre': 'Revoque Grueso',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '5,05',
        'descripcion': 'Jaharro y enlucido a la cal terminado al fieltro',
        'unidad': 'm2',
        'precio_unitario': 17537.85,
        'etapa_nombre': 'Revoque Grueso',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '6.02',
        'descripcion': 'Jaharro bajo revestimiento',
        'unidad': 'm2',
        'precio_unitario': 15477.65,
        'etapa_nombre': 'Revoque Fino',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '6.03',
        'descripcion': 'Emprolijado de hormigón  visto',
        'unidad': 'm2',
        'precio_unitario': 10839.77,
        'etapa_nombre': 'Revoque Fino',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '7.01',
        'descripcion': 'Emprolijado de hormigón visto',
        'unidad': 'm2',
        'precio_unitario': 10839.77,
        'etapa_nombre': 'Cielorrasos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '7.02',
        'descripcion': 'Armado de placa de roca de yeso con buña perimetral.',
        'unidad': 'm2',
        'precio_unitario': 24363.69,
        'etapa_nombre': 'Cielorrasos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '7.03',
        'descripcion': 'Armado de placa de roca de yeso con buña perimetral para locales húmedos según sistema adoptado según PET Particulares.',
        'unidad': 'm2',
        'precio_unitario': 26856.18,
        'etapa_nombre': 'Cielorrasos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '7.05',
        'descripcion': 'Cajones en placa roca yeso',
        'unidad': 'ml',
        'precio_unitario': 24363.69,
        'etapa_nombre': 'Cielorrasos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '7.06',
        'descripcion': 'Traforos,  gargantas y refuerzos para iluminación, tapas de acceso, detección inc,  etc.',
        'unidad': 'gl',
        'precio_unitario': 1417672.43,
        'etapa_nombre': 'Cielorrasos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '7.07',
        'descripcion': 'Tapas de inspeccion del sistema',
        'unidad': 'unidades',
        'precio_unitario': 77611.51,
        'etapa_nombre': 'Cielorrasos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '7.08',
        'descripcion': 'Aplicado de yeso en ambientes principales',
        'unidad': 'm2',
        'precio_unitario': 24194.32,
        'etapa_nombre': 'Cielorrasos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '7.09',
        'descripcion': 'Buña perimetral sobre cielorrasos aplicados de yeso.',
        'unidad': 'ml',
        'precio_unitario': 1288.79,
        'etapa_nombre': 'Cielorrasos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '8.01',
        'descripcion': 'Contrapiso  5ºss  / de hormigón armado  sobre terreno. -Malla sima sup e inferior  ø8 c/15 / sobre capa drenante y canaletas perimetrales (espesor según doc. Grafica)',
        'unidad': 'm2',
        'precio_unitario': 58367.8,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '8.02',
        'descripcion': 'Contrapiso  4to ss / de hormigón armado  con y sin pendiente-Malla sima ø8c/15.  (bajo piso de terminacion) . Canaletas perimetrales (espesor según doc. Grafica)',
        'unidad': 'm2',
        'precio_unitario': 58367.8,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '8.03',
        'descripcion': 'Contrapiso de hormigón armado h21 esp 15cm  con y sin pendiente-Malla sima ø 4,2c/15 en veredas',
        'unidad': 'm2',
        'precio_unitario': 29436.93,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '8.04',
        'descripcion': 'Contrapiso sobre terreno compactado H° de cascote',
        'unidad': 'm2',
        'precio_unitario': 22760.97,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '8.06',
        'descripcion': 'Contrapiso  de hormigón pobre  s/PET',
        'unidad': 'm2',
        'precio_unitario': 13089.89,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '8.07',
        'descripcion': 'Contrapiso  de hormigón pobre sobre losa  con canaletas de drenaje s/PET',
        'unidad': 'm2',
        'precio_unitario': 13089.89,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '8.09',
        'descripcion': 'Contrapiso alivianado (tipo Isocret d=350) con pendiente para azotea',
        'unidad': 'm2',
        'precio_unitario': 26105.28,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '8.1',
        'descripcion': 'Babetas',
        'unidad': 'ml',
        'precio_unitario': 5221.06,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '8.11',
        'descripcion': 'Carpeta de nivelación tradicional',
        'unidad': 'm2',
        'precio_unitario': 8249.58,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '8.12',
        'descripcion': 'Carpeta monolítica marca y tipo a definir por DDO',
        'unidad': 'm2',
        'precio_unitario': 12666.56,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '8.13',
        'descripcion': 'Carpeta de nivelación  bajo techado, sobre losas planas en azoteas y balcones con pendiente con babeta perimetral y cierre de la misma',
        'unidad': 'm2',
        'precio_unitario': 8249.58,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '8.14',
        'descripcion': 'Carpeta de protección sobre techados / aislaciones',
        'unidad': 'm2',
        'precio_unitario': 10020.12,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '8.15',
        'descripcion': 'Carpetas en SS',
        'unidad': 'm2',
        'precio_unitario': 8249.58,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '9.01',
        'descripcion': 'Provisión y colocación de bloques intertrabados de H° en 4°SS sobre manto de arena',
        'unidad': 'm2',
        'precio_unitario': 38250.37,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '9.02',
        'descripcion': 'Pavimento de hormigón armado según PET c/endurecedor no metálico color negro con vainillas  antideslizantes tipo espina de pescado. Canaletas central y laterales p/evacuación de agua. Alisado de cemento en banquinas',
        'unidad': 'm2',
        'precio_unitario': 43468.88,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '9.03',
        'descripcion': 'Pavimento de rodamiento llaneado mecánico  s/ PET con endurecedor no metálico  color a definir . 80mm. Incluye malla,  juntas de dilatación y sellados',
        'unidad': 'm2',
        'precio_unitario': 38641.38,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '9.04',
        'descripcion': 'Cemento alisado con endurecedor no metálico  color  según indicaciones DO. Incluye juntas de dilatacion',
        'unidad': 'm2',
        'precio_unitario': 31985.63,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '9.06',
        'descripcion': 'Escaleras: Cemento alisado rodillado espesor a definir con endurecedor metálico color a definir  s/PET/ con perfil  "L" 25x25x3mm./  Incluye terminacion reglamentaria. Ley  962',
        'unidad': 'm2',
        'precio_unitario': 30832.81,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '9.07',
        'descripcion': 'Colocación de Porcellanato  en locales sanitarios',
        'unidad': 'm2',
        'precio_unitario': 22327.92,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '9.08000000000001',
        'descripcion': 'Colocación de Porcellanato  en:\n Balcones/  patios / terrazas UF',
        'unidad': 'm2',
        'precio_unitario': 22327.92,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '9.09000000000001',
        'descripcion': 'Porcellanato en espacios comunes (Solo colocación)',
        'unidad': 'm2',
        'precio_unitario': 22327.92,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '9.10000000000001',
        'descripcion': 'Colocación porcellanatos en depósitos o loc. Sº según Pl Locales',
        'unidad': 'm2',
        'precio_unitario': 22327.92,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '9.11000000000001',
        'descripcion': 'Provisón y colocación de baldosones de vereda reglamentarios /  Incluye juntas de dilatacion',
        'unidad': 'm2',
        'precio_unitario': 29284.41,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '9.12000000000001',
        'descripcion': 'Colocación Deck de hormigón sobre estructura de apoyo',
        'unidad': 'm2',
        'precio_unitario': 15035.92,
        'etapa_nombre': 'Contrapisos y Carpetas',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '10.01',
        'descripcion': 'Cemento alisado para pintar  h:10cm',
        'unidad': 'ml',
        'precio_unitario': 11229.28,
        'etapa_nombre': 'Pisos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '10.02',
        'descripcion': 'Porcellanato idem  Piso  h: 10 cm -    (solo colocación)',
        'unidad': 'ml',
        'precio_unitario': 6490.71,
        'etapa_nombre': 'Pisos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '10.03',
        'descripcion': 'Porcellanato idem  Piso  h: 10 cm -  (solo colocación) con canaleta-desagüe en balcones, terrazas y/o patios',
        'unidad': 'ml',
        'precio_unitario': 6490.71,
        'etapa_nombre': 'Pisos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '10.04',
        'descripcion': 'Rampante de cemento alisado reforzado  p/pintar con buña S/ PET',
        'unidad': 'ml',
        'precio_unitario': 12118.66,
        'etapa_nombre': 'Pisos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '10.06',
        'descripcion': 'Zocalos prepintados MDF (Sólo colocación - CIRC Nº 5)',
        'unidad': 'ml',
        'precio_unitario': 6443.97,
        'etapa_nombre': 'Pisos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '10.07',
        'descripcion': 'Agregado: Cemento alisado para pintar h: 20cm',
        'unidad': 'ml',
        'precio_unitario': 12162.59,
        'etapa_nombre': 'Pisos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '11.01',
        'descripcion': 'Tarquini o similar, buñado, rodillado y color a definir (incl provision)',
        'unidad': 'm2',
        'precio_unitario': 19324.15,
        'etapa_nombre': 'Revestimientos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '11.02',
        'descripcion': 'Tarquini o similar, buñado, llaneado y color a definir (incl provision)',
        'unidad': 'm2',
        'precio_unitario': 19324.15,
        'etapa_nombre': 'Revestimientos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '11.03',
        'descripcion': 'Colocación Porcellanato en baños',
        'unidad': 'm2',
        'precio_unitario': 22327.92,
        'etapa_nombre': 'Revestimientos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '11.04',
        'descripcion': 'Colocacion Porcellanato en offices o cocinas',
        'unidad': 'm2',
        'precio_unitario': 22327.92,
        'etapa_nombre': 'Revestimientos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '12.02',
        'descripcion': 'Enlucido de Yeso proyectado',
        'unidad': 'm2',
        'precio_unitario': 22469.91,
        'etapa_nombre': 'Yesería y Enlucidos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '12.04',
        'descripcion': 'Cantoneras metálicas',
        'unidad': 'ml',
        'precio_unitario': 4283.43,
        'etapa_nombre': 'Yesería y Enlucidos',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.01',
        'descripcion': 'Provisión y colocación de Perfil de hierro "L" de 11/4" en cantos vivos h=1,20m',
        'unidad': 'gl',
        'precio_unitario': 2079264.38,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.02',
        'descripcion': 'Provisión y colocación de Perfil de Acero Iº en solias, umbrales y flejes en todas las puertas y cambio de solados .(Incluye mano de obra y mat. Aporte)',
        'unidad': 'gl',
        'precio_unitario': 13084881.11,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.03',
        'descripcion': 'Provisión y colocación de Guardacantos y /o solias Aluminio (tipo Atrim o similar) (Se consideran en locales de servicio)',
        'unidad': 'gl',
        'precio_unitario': 4719334.83,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.04',
        'descripcion': 'Provisión y colocación de guardacantos en  en AI en aristas salientes en revestimientos porcellanatos (Se consideran en locales de primera)',
        'unidad': 'gl',
        'precio_unitario': 17104113.46,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.05',
        'descripcion': 'Provisión y colocación deTapas de hormigón  s/ PET',
        'unidad': 'gl',
        'precio_unitario': 3278684.48,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.06',
        'descripcion': 'Provisión y colocación Bocas de ataque',
        'unidad': 'unidades',
        'precio_unitario': 38795.25,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.07',
        'descripcion': 'Provisión y colocación de topes de estacionamiento',
        'unidad': 'unidades',
        'precio_unitario': 13498.95,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.08',
        'descripcion': 'Colocación de accesorios de baños',
        'unidad': 'unidades',
        'precio_unitario': 22162.74,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.09',
        'descripcion': 'Colocación de bañeras',
        'unidad': 'gl',
        'precio_unitario': 12558888.99,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.1',
        'descripcion': 'Sellado perimetral de Bañeras c/ revestimiento',
        'unidad': 'gl',
        'precio_unitario': 275229.82,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.11',
        'descripcion': 'Sellados en encuentros de buñas, carpinterías y varios',
        'unidad': 'gl',
        'precio_unitario': 12591843.86,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.12',
        'descripcion': 'Sellados en placas asegurando hermeticidad  acústica',
        'unidad': 'gl',
        'precio_unitario': 20475595.87,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.13',
        'descripcion': 'Selladores  según PET.',
        'unidad': 'gl',
        'precio_unitario': 362846.7,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.14',
        'descripcion': 'Colocaciones y/o  amures de= escaleras marineras, ménsulas para apoyo de  termotanques o calderas, marcos felpudo, cajas de piso. Sujeción de bandejas portacables.  (No incluye sujeción bandejas portacables)',
        'unidad': 'gl',
        'precio_unitario': 178520.51,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.15',
        'descripcion': 'Provisión y colocación de Platabandas para fijación de barandas y pasamanos y todo accesorios metálico o prefabricado necesario',
        'unidad': 'gl',
        'precio_unitario': 3037480.3,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.16',
        'descripcion': 'Provisión y colocación de  rejas en conductos evacuación de humos,  rejas y rejillas de ventilaciones metálicas correspondientes al sist.de vent.natural por conducto. Ventilaciones  reglamentarias de gas.',
        'unidad': 'gl',
        'precio_unitario': 5888292.35,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.17',
        'descripcion': 'Provisión y amure de tapas  de  conexiones de servicios,  pozos de bombeo,  tapas de cámaras cloacal, inspección,  hierro ángulo para colocación de rejas, guardaganado, tapas en gral , gabinetes y tapas para incendio,, rejillas de desague de piso, etc.; tapas de A°A°, difusores,  soportes equipos de A°A.  (Sólo se contempla tapa de pozo de bombeo por falta de documentación)',
        'unidad': 'gl',
        'precio_unitario': 209634.28,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.18',
        'descripcion': 'Amure de premarcos,  marcos de puertas, carpinterías de plenos . de carpinterias generales, de cerramientos perimetrales exteriores  y portones de acceso.',
        'unidad': 'gl',
        'precio_unitario': 43630412.37,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.19',
        'descripcion': 'Amure de umbrales y marcos de puertas de ascensor',
        'unidad': 'gl',
        'precio_unitario': 5081746.91,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.2',
        'descripcion': 'Amure de ; escaleras y divisores de bajorrecorridos y ganchos para montaje.prevision de desagüe en bajo recorrido.bases de equipos ascensores s/indic.del proveedor; anclaje de ganchos.',
        'unidad': 'gl',
        'precio_unitario': 251070.57,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.21',
        'descripcion': 'Ejecucion de base para resorte y amure del mismo en bajo recorrido de asecensores',
        'unidad': 'gl',
        'precio_unitario': 144241.62,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.22',
        'descripcion': 'Provisión e instalación  de defensas altura mínima de 1,20 m, para protección de las entradas a los pasadizos',
        'unidad': 'gl',
        'precio_unitario': 281420.16,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.23',
        'descripcion': 'Insertos para silletero o mudanzas en azotea',
        'unidad': 'gl',
        'precio_unitario': 302048.22,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.24',
        'descripcion': 'Provisión y colocación de ménsulas bajomesadas',
        'unidad': 'unidades',
        'precio_unitario': 16243.58,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.25',
        'descripcion': 'Previsión para colgar bicicletas',
        'unidad': 'gl',
        'precio_unitario': 215867.17,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.26',
        'descripcion': 'Amure y ay.gr  de  Parrilla (Sin especificaciones en PET)',
        'unidad': 'gl',
        'precio_unitario': 400188.26,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.27',
        'descripcion': 'Amure y ay.gr  de  Pergola (Sin especificaciones en PET)',
        'unidad': 'gl',
        'precio_unitario': 2067327.82,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '13.29',
        'descripcion': 'Agregado: Hierro ángulo en cantos vivos de banquinas en rampa vehicular (1 3/16")',
        'unidad': 'gl',
        'precio_unitario': 736211.74,
        'etapa_nombre': 'Provisiones y Colocaciones',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14.01',
        'descripcion': 'Provisión y Colocación de Cierres cortafuegos en plenos (Se tomaron en cuenta plenos en 1º Piso según pliego)',
        'unidad': 'gl',
        'precio_unitario': 18764796.92,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14.02',
        'descripcion': 'Limpieza integral  y prueba de funcionamiento de desagües  Cloacales y Pluviales al final de la obra.',
        'unidad': 'gl',
        'precio_unitario': 2835344.87,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14.03',
        'descripcion': 'Ejecución de canteros areas exteriores /cazoletas en veredas,etc / Provisión y colocación alcorque en cantero vereda',
        'unidad': 'gl',
        'precio_unitario': 1568454.01,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14.04',
        'descripcion': 'Escalones, desniveles en mampostería planta baja, canaletas y varios. \nCanaletas para desagües pluviales. incl. amure de rejillas (Se considera sólo colocación de guardaganado en acceso a cocheras PB)',
        'unidad': 'gl',
        'precio_unitario': 93799.7,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14.05',
        'descripcion': 'Nivelación y reparación de cordones o ejecución nuevo en veredas de calle. Rebajes de cordón para entrada vehicular',
        'unidad': 'gl',
        'precio_unitario': 430407.46,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14.06',
        'descripcion': 'Ejecución gabinetes reguladores de gas con puerta reglamentaria',
        'unidad': 'gl',
        'precio_unitario': 2549702.49,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14.07',
        'descripcion': 'Equipos de ventilación de subsuelo: ejecución de bases /   Bases antivibratorias para equipos según indicaciones de proveedores. Ejecución de bases para equipos en  azotea',
        'unidad': 'gl',
        'precio_unitario': 758458.34,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14.08',
        'descripcion': 'Buña z en cielorrasos de placa de yeso.',
        'unidad': 'ml',
        'precio_unitario': 3221.98,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14.1',
        'descripcion': 'Bases para equipos en azotea y varios. \nCanaletas para desagües pluviales. incl. amure de rejillas (No se contempla colocación de canaletas por falta de documentación)',
        'unidad': 'gl',
        'precio_unitario': 2481435.08,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14.11',
        'descripcion': 'Bases de equipos de aire acondicionado y ventilaciones. y varios. \nCanaletas para desagües pluviales. incl. amure de rejillas (No se contempla colocación de canaletas por falta de documentación)',
        'unidad': 'gl',
        'precio_unitario': 3024759.16,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14.12',
        'descripcion': 'Prov y colocación de protecciones para  terminaciones y elementos  hasta entrega obra',
        'unidad': 'gl',
        'precio_unitario': 18839195.71,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14.14',
        'descripcion': 'Ejecucion de obra civil de CAMARA TRANSFORMADORA (incluye provision de herrerias reglamentarias y pintura)',
        'unidad': 'gl',
        'precio_unitario': 26412672.27,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14,15 a',
        'descripcion': 'Agregado: Junta de dilatación de 1º Piso a AZ (en encuentro tabiques y pisos)',
        'unidad': 'gl',
        'precio_unitario': 1228823.1,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14,15 b',
        'descripcion': 'Agregado: Provisión de guardaganado para Item 14.04',
        'unidad': 'gl',
        'precio_unitario': 288903.08,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
    {
        'constructora': 'Cortes y Sistemas',
        'codigo': '14,15 c',
        'descripcion': 'Agregado: Buñas en medianeras, coincidente con lomo de losa y fondo de viga',
        'unidad': 'gl',
        'precio_unitario': 18124509.56,
        'etapa_nombre': 'Instalaciones Complementarias',
        'planilla': 'albanileria',
    },
]
