"""Base Tecnica de Computos OBYRA.

Diccionario estructurado de reglas tecnicas para reconocer items de obra
durante el analisis IA de presupuestos. Sirve como referencia interna
para clasificar:
  - Rubro y etapa estandar.
  - Unidad de medida esperada y criterio de medicion.
  - Materiales, mano de obra y maquinaria asociados.
  - Rendimiento y desperdicio orientativos.
  - Confianza base.

DISCLAIMER:
  Las reglas estan inspiradas en bibliografia tecnica clasica de la
  construccion argentina (criterios generales de computos y presupuestos),
  pero los valores especificos (rendimientos, desperdicios, listas de
  materiales) son criterios internos de OBYRA, simplificados y editables.
  No se reproducen textos literales ni fragmentos extensos de obras
  protegidas por derechos de autor.

Estructura de cada regla:
    'id'                    : str unico (slug)
    'rubro'                 : str legible (ver RUBROS_RECONOCIDOS)
    'etapa'                 : nombre de etapa estandar (compatible con etapa_matcher)
    'tarea'                 : descripcion canonica de la tarea
    'unidad_esperada'       : codigo de unidad (m2, m3, m, kg, etc.)
    'unidades_validas'      : lista de unidades aceptadas como sinonimos
    'criterio_medicion'     : texto breve de como se mide
    'palabras_clave_fuertes': matches >= 1 -> alta confianza
    'palabras_clave_medias' : matches >= 1 -> media confianza
    'palabras_clave_debiles': matches >= 1 -> baja confianza
    'palabras_excluyentes'  : si aparece alguna -> NO match (ej: "demolicion de muro" no es muro nuevo)
    'materiales_sugeridos'  : list[str]
    'mano_obra_sugerida'    : list[str]
    'maquinaria_sugerida'   : list[str]
    'rendimiento_estimado'  : texto orientativo
    'desperdicio_estimado'  : porcentaje orientativo
    'observaciones_tecnicas': texto breve
    'fuente'                : siempre 'criterio interno OBYRA'
"""
from __future__ import annotations


RUBROS_RECONOCIDOS = [
    'Preliminares y Organización',
    'Movimiento de Suelos',
    'Fundaciones',
    'Estructura de Hormigón Armado',
    'Albañilería',
    'Revoques y Terminaciones',
    'Pisos y Revestimientos',
    'Cubiertas e Impermeabilización',
    'Instalación Eléctrica',
    'Instalación Sanitaria',
    'Instalación de Gas',
    'Carpinterías',
    'Pintura',
    'Equipos y Maquinaria',
    'Limpieza y Entrega Final',
]


REGLAS_TECNICAS = [
    # ============================================================
    # 1. PRELIMINARES Y ORGANIZACION
    # ============================================================
    {
        'id': 'obrador',
        'rubro': 'Preliminares y Organización',
        'etapa': 'Preliminares y Organizacion',
        'tarea': 'Obrador de obra',
        'unidad_esperada': 'gl',
        'unidades_validas': ['gl', 'global', 'unidad'],
        'criterio_medicion': 'Suma global por presencia (incluye container, baño químico, agua, energía).',
        'palabras_clave_fuertes': ['obrador'],
        'palabras_clave_medias': ['contenedor de obra', 'container'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Container o trailer', 'Generador eléctrico', 'Baño químico', 'Provisión de agua'],
        'mano_obra_sugerida': ['Sereno', 'Encargado de obrador'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '1 obrador por obra',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Computar por mes de duración estimada de obra.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'cartel_obra',
        'rubro': 'Preliminares y Organización',
        'etapa': 'Preliminares y Organizacion',
        'tarea': 'Cartel de obra reglamentario',
        'unidad_esperada': 'unidad',
        'unidades_validas': ['un', 'unidad', 'gl'],
        'criterio_medicion': 'Por unidad de cartel reglamentario.',
        'palabras_clave_fuertes': ['cartel de obra', 'cartel reglamentario'],
        'palabras_clave_medias': ['cartel'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Chapa galvanizada', 'Estructura metálica', 'Vinilo impreso'],
        'mano_obra_sugerida': ['Oficial', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '1 jornal cuadrilla',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Verificar dimensiones según ordenanza municipal.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'replanteo',
        'rubro': 'Preliminares y Organización',
        'etapa': 'Preliminares y Organizacion',
        'tarea': 'Replanteo de obra',
        'unidad_esperada': 'gl',
        'unidades_validas': ['gl', 'global', 'm2'],
        'criterio_medicion': 'Global o por m² de superficie de obra.',
        'palabras_clave_fuertes': ['replanteo'],
        'palabras_clave_medias': ['estaqueado', 'amojonamiento'],
        'palabras_clave_debiles': ['marcacion'],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Estacas de madera', 'Hilo de marcar', 'Cal en pasta'],
        'mano_obra_sugerida': ['Topógrafo', 'Oficial', 'Ayudante'],
        'maquinaria_sugerida': ['Nivel topográfico', 'Estación total'],
        'rendimiento_estimado': '1-2 jornales para vivienda chica',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Confirmar puntos contra mensura y plano de obra.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'cerco_obra',
        'rubro': 'Preliminares y Organización',
        'etapa': 'Preliminares y Organizacion',
        'tarea': 'Cerco perimetral de obra',
        'unidad_esperada': 'm',
        'unidades_validas': ['m', 'ml', 'metro'],
        'criterio_medicion': 'Metro lineal de cerco montado.',
        'palabras_clave_fuertes': ['cerco de obra', 'vallado de obra', 'cerco perimetral'],
        'palabras_clave_medias': ['cerco', 'vallado', 'valla'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Postes', 'Media sombra', 'Chapa lisa', 'Tornillería'],
        'mano_obra_sugerida': ['Oficial', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '15-20 m por jornal',
        'desperdicio_estimado': '5%',
        'observaciones_tecnicas': 'Cumplir altura mínima 2.10 m según municipio.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'limpieza_inicial',
        'rubro': 'Preliminares y Organización',
        'etapa': 'Preliminares y Organizacion',
        'tarea': 'Limpieza inicial del terreno',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie limpiada/desmalezada.',
        'palabras_clave_fuertes': ['limpieza inicial', 'desmalezado'],
        'palabras_clave_medias': ['limpieza terreno', 'preparacion del terreno'],
        'palabras_clave_debiles': ['limpieza'],
        'palabras_excluyentes': ['final', 'entrega'],
        'materiales_sugeridos': [],
        'mano_obra_sugerida': ['Oficial', 'Ayudante'],
        'maquinaria_sugerida': ['Desmalezadora', 'Volquete'],
        'rendimiento_estimado': '50-100 m²/jornal según vegetación',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Incluye retiro de escombro y vegetación al volquete.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'jefe_obra',
        'rubro': 'Preliminares y Organización',
        'etapa': 'Preliminares y Organizacion',
        'tarea': 'Jefatura de obra / supervisión',
        'unidad_esperada': 'mes',
        'unidades_validas': ['mes', 'meses', 'gl'],
        'criterio_medicion': 'Sueldo mensual × duración estimada.',
        'palabras_clave_fuertes': ['jefe de obra', 'supervision', 'representante tecnico', 'jefatura de obra'],
        'palabras_clave_medias': ['supervisor', 'capataz'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': [],
        'mano_obra_sugerida': ['Jefe de obra', 'Capataz'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': 'Asignación full-time',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Considerar cargas sociales sobre el sueldo bruto.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 2. MOVIMIENTO DE SUELOS
    # ============================================================
    {
        'id': 'excavacion_general',
        'rubro': 'Movimiento de Suelos',
        'etapa': 'Movimiento de Suelos',
        'tarea': 'Excavación general',
        'unidad_esperada': 'm3',
        'unidades_validas': ['m3', 'm³'],
        'criterio_medicion': 'Volumen excavado en estado natural × largo × ancho × profundidad.',
        'palabras_clave_fuertes': ['excavacion', 'excavación'],
        'palabras_clave_medias': ['movimiento de suelo', 'desmonte'],
        'palabras_clave_debiles': ['cavar', 'pozo'],
        'palabras_excluyentes': [],
        'materiales_sugeridos': [],
        'mano_obra_sugerida': ['Oficial', 'Ayudante'],
        'maquinaria_sugerida': ['Retroexcavadora', 'Camión volcador', 'Pala mecánica'],
        'rendimiento_estimado': '50-100 m³/día con retro',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Incluye carga y retiro de material.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'relleno_compactado',
        'rubro': 'Movimiento de Suelos',
        'etapa': 'Movimiento de Suelos',
        'tarea': 'Relleno compactado con tosca',
        'unidad_esperada': 'm3',
        'unidades_validas': ['m3', 'm³'],
        'criterio_medicion': 'Volumen colocado y compactado por capas de 20-30 cm.',
        'palabras_clave_fuertes': ['relleno compactado', 'relleno con tosca', 'tosca compactada'],
        'palabras_clave_medias': ['relleno', 'tosca', 'compactacion'],
        'palabras_clave_debiles': ['nivelacion'],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Tosca', 'Suelo seleccionado'],
        'mano_obra_sugerida': ['Oficial', 'Ayudante'],
        'maquinaria_sugerida': ['Vibroapisonador', 'Rodillo compactador'],
        'rendimiento_estimado': '20-40 m³/día con compactador',
        'desperdicio_estimado': '15% por densificación',
        'observaciones_tecnicas': 'Compactar al 95% Proctor Estándar.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'depresion_napa',
        'rubro': 'Movimiento de Suelos',
        'etapa': 'Depresion de Napa',
        'tarea': 'Depresión de napa freática / bombeo',
        'unidad_esperada': 'gl',
        'unidades_validas': ['gl', 'global', 'mes', 'dia'],
        'criterio_medicion': 'Global o por mes según duración.',
        'palabras_clave_fuertes': ['depresion de napa', 'depresión de napa', 'bombeo de napa'],
        'palabras_clave_medias': ['napa', 'achique', 'bombeo'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Caños drenaje', 'Filtros', 'Mangueras'],
        'mano_obra_sugerida': ['Oficial'],
        'maquinaria_sugerida': ['Bomba sumergible', 'Generador'],
        'rendimiento_estimado': 'Continuo durante fundaciones',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Coordinar con vecinos por descarga.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 3. FUNDACIONES
    # ============================================================
    {
        'id': 'hormigon_limpieza',
        'rubro': 'Fundaciones',
        'etapa': 'Fundaciones',
        'tarea': 'Hormigón de limpieza H8',
        'unidad_esperada': 'm3',
        'unidades_validas': ['m3', 'm³'],
        'criterio_medicion': 'Volumen × espesor 5-10 cm bajo zapatas/platea.',
        'palabras_clave_fuertes': ['hormigon de limpieza', 'hormigón de limpieza', 'h8'],
        'palabras_clave_medias': ['hormigon limpieza'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Hormigón H8', 'Encofrado lateral'],
        'mano_obra_sugerida': ['Oficial', 'Ayudante'],
        'maquinaria_sugerida': ['Mixer'],
        'rendimiento_estimado': '20-30 m³/jornada',
        'desperdicio_estimado': '5%',
        'observaciones_tecnicas': 'Espesor mínimo 5 cm.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'platea_fundacion',
        'rubro': 'Fundaciones',
        'etapa': 'Fundaciones',
        'tarea': 'Platea de fundación de hormigón armado',
        'unidad_esperada': 'm3',
        'unidades_validas': ['m3', 'm³', 'm2', 'm²'],
        'criterio_medicion': 'm³ de hormigón colocado o m² × espesor.',
        'palabras_clave_fuertes': ['platea de fundacion', 'platea de fundación', 'platea h21'],
        'palabras_clave_medias': ['platea'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Hormigón H21', 'Hierro 8mm', 'Hierro 10mm', 'Encofrado', 'Malla SIMA'],
        'mano_obra_sugerida': ['Oficial estructurista', 'Ayudante', 'Armador'],
        'maquinaria_sugerida': ['Mixer', 'Vibrador de inmersión'],
        'rendimiento_estimado': '50-80 m³/día con bomba',
        'desperdicio_estimado': '5% hormigón / 8% hierro',
        'observaciones_tecnicas': 'Verificar recubrimiento mínimo 3 cm en hierros.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'zapata_corrida',
        'rubro': 'Fundaciones',
        'etapa': 'Fundaciones',
        'tarea': 'Zapata corrida / base / cabezal',
        'unidad_esperada': 'm3',
        'unidades_validas': ['m3', 'm³', 'unidad'],
        'criterio_medicion': 'm³ de hormigón armado por zapata o cabezal.',
        'palabras_clave_fuertes': ['zapata corrida', 'cabezal de pilote', 'base aislada'],
        'palabras_clave_medias': ['zapata', 'cabezal', 'base'],
        'palabras_clave_debiles': ['cimiento'],
        'palabras_excluyentes': ['ladrillo', 'mamposteria'],
        'materiales_sugeridos': ['Hormigón H21', 'Hierro 8mm', 'Hierro 12mm', 'Encofrado'],
        'mano_obra_sugerida': ['Oficial estructurista', 'Ayudante'],
        'maquinaria_sugerida': ['Mixer', 'Vibrador'],
        'rendimiento_estimado': '8-15 unidades/jornada',
        'desperdicio_estimado': '5%',
        'observaciones_tecnicas': 'Verificar cota de fundación según estudio de suelos.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'pilote_pilotin',
        'rubro': 'Fundaciones',
        'etapa': 'Fundaciones',
        'tarea': 'Pilote / pilotín perforado',
        'unidad_esperada': 'm',
        'unidades_validas': ['m', 'ml', 'unidad'],
        'criterio_medicion': 'Metro lineal perforado y hormigonado.',
        'palabras_clave_fuertes': ['pilote', 'pilotin', 'pilotín'],
        'palabras_clave_medias': [],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Hormigón', 'Hierro estructural', 'Bentonita'],
        'mano_obra_sugerida': ['Oficial pilotero', 'Ayudante'],
        'maquinaria_sugerida': ['Equipo de perforación', 'Rotativa'],
        'rendimiento_estimado': '20-40 m/día',
        'desperdicio_estimado': '8%',
        'observaciones_tecnicas': 'Verificar profundidad y diámetro según cálculo.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 4. ESTRUCTURA DE HORMIGON ARMADO
    # ============================================================
    {
        'id': 'hormigon_h21',
        'rubro': 'Estructura de Hormigón Armado',
        'etapa': 'Estructura de Hormigon Armado',
        'tarea': 'Hormigón armado H21 (columnas/vigas/losas)',
        'unidad_esperada': 'm3',
        'unidades_validas': ['m3', 'm³'],
        'criterio_medicion': 'm³ de hormigón colocado.',
        'palabras_clave_fuertes': ['hormigon h21', 'hormigón h21', 'h21', 'hormigon armado'],
        'palabras_clave_medias': ['hormigon estructural', 'h°a°', 'hºaº'],
        'palabras_clave_debiles': ['hormigon'],
        'palabras_excluyentes': ['limpieza', 'pobre', 'h8'],
        'materiales_sugeridos': ['Hormigón H21 elaborado', 'Hierro estructural', 'Encofrado', 'Malla SIMA'],
        'mano_obra_sugerida': ['Oficial estructurista', 'Encofrador', 'Armador', 'Ayudante'],
        'maquinaria_sugerida': ['Mixer', 'Bomba de hormigón', 'Vibrador de inmersión'],
        'rendimiento_estimado': '15-25 m³/día con bomba',
        'desperdicio_estimado': '5%',
        'observaciones_tecnicas': 'Verificar resistencia a 28 días con probetas.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'losa_hormigon',
        'rubro': 'Estructura de Hormigón Armado',
        'etapa': 'Estructura de Hormigon Armado',
        'tarea': 'Losa de hormigón armado',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²', 'm3'],
        'criterio_medicion': 'm² × espesor o m³ directo.',
        'palabras_clave_fuertes': ['losa de hormigon', 'losa h°a°', 'losa hormigon armado'],
        'palabras_clave_medias': ['losa', 'losa maciza'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Hormigón H21', 'Hierro 8mm', 'Hierro 6mm', 'Encofrado', 'Apuntalamiento'],
        'mano_obra_sugerida': ['Oficial', 'Encofrador', 'Armador'],
        'maquinaria_sugerida': ['Bomba de hormigón', 'Vibrador'],
        'rendimiento_estimado': '50-100 m²/día',
        'desperdicio_estimado': '5%',
        'observaciones_tecnicas': 'Espesor típico 12-15 cm. Apuntalar 21 días mín.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'columna_hormigon',
        'rubro': 'Estructura de Hormigón Armado',
        'etapa': 'Estructura de Hormigon Armado',
        'tarea': 'Columna de hormigón armado',
        'unidad_esperada': 'm3',
        'unidades_validas': ['m3', 'm³', 'unidad'],
        'criterio_medicion': 'm³ por columna (sección × altura).',
        'palabras_clave_fuertes': ['columna de hormigon', 'columna h°a°', 'columna h21'],
        'palabras_clave_medias': ['columna'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Hormigón H21', 'Hierro 12mm', 'Hierro 10mm', 'Estribos 6mm', 'Encofrado'],
        'mano_obra_sugerida': ['Oficial', 'Encofrador', 'Armador'],
        'maquinaria_sugerida': ['Mixer', 'Vibrador'],
        'rendimiento_estimado': '5-10 columnas/día',
        'desperdicio_estimado': '5%',
        'observaciones_tecnicas': 'Recubrimiento mínimo 2 cm.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'viga_hormigon',
        'rubro': 'Estructura de Hormigón Armado',
        'etapa': 'Estructura de Hormigon Armado',
        'tarea': 'Viga de hormigón armado',
        'unidad_esperada': 'm3',
        'unidades_validas': ['m3', 'm³', 'm', 'ml'],
        'criterio_medicion': 'm³ por viga (sección × largo).',
        'palabras_clave_fuertes': ['viga de hormigon', 'viga h°a°', 'viga h21'],
        'palabras_clave_medias': ['viga'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Hormigón H21', 'Hierro estructural', 'Estribos', 'Encofrado'],
        'mano_obra_sugerida': ['Oficial', 'Encofrador', 'Armador'],
        'maquinaria_sugerida': ['Mixer', 'Vibrador'],
        'rendimiento_estimado': '10-15 m³/día',
        'desperdicio_estimado': '5%',
        'observaciones_tecnicas': 'Verificar empalmes con columnas.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'encofrado',
        'rubro': 'Estructura de Hormigón Armado',
        'etapa': 'Estructura de Hormigon Armado',
        'tarea': 'Encofrado y desencofrado',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie de encofrado en contacto con hormigón.',
        'palabras_clave_fuertes': ['encofrado', 'desencofrado'],
        'palabras_clave_medias': [],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Tableros fenólicos', 'Tirantes', 'Puntales', 'Clavos', 'Desencofrante'],
        'mano_obra_sugerida': ['Encofrador', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '15-25 m²/jornal',
        'desperdicio_estimado': '10%',
        'observaciones_tecnicas': 'Reutilización promedio 5-7 veces.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'armadura_hierro',
        'rubro': 'Estructura de Hormigón Armado',
        'etapa': 'Estructura de Hormigon Armado',
        'tarea': 'Armadura de hierro estructural',
        'unidad_esperada': 'kg',
        'unidades_validas': ['kg', 'tn'],
        'criterio_medicion': 'Kilos de hierro doblado y atado.',
        'palabras_clave_fuertes': ['armadura', 'hierro estructural', 'acero estructural'],
        'palabras_clave_medias': ['hierro', 'acero', 'hierros'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': ['malla', 'sima', 'soldado'],
        'materiales_sugeridos': ['Hierro 6/8/10/12/16mm', 'Alambre de atar'],
        'mano_obra_sugerida': ['Armador', 'Ayudante'],
        'maquinaria_sugerida': ['Cortadora-dobladora'],
        'rendimiento_estimado': '200-300 kg/jornal',
        'desperdicio_estimado': '8%',
        'observaciones_tecnicas': 'Cómputo según planilla de hierros del proyectista.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 5. ALBAÑILERIA / MAMPOSTERIA
    # ============================================================
    {
        'id': 'mamposteria_ladrillo_hueco_12',
        'rubro': 'Albañilería',
        'etapa': 'Mamposteria',
        'tarea': 'Mampostería ladrillo hueco 12 cm',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie neta (largo × alto) restando vanos > 1 m².',
        'palabras_clave_fuertes': ['ladrillo hueco 12', 'ladrillo hueco 12cm', 'mamposteria 12', 'mamposteria de 12'],
        'palabras_clave_medias': ['ladrillo hueco', 'mamposteria de hueco'],
        'palabras_clave_debiles': ['hueco'],
        'palabras_excluyentes': ['demolicion', 'demoler'],
        'materiales_sugeridos': ['Ladrillo hueco 12', 'Cemento', 'Arena gruesa', 'Cal', 'Mortero adhesivo'],
        'mano_obra_sugerida': ['Oficial albañil', 'Ayudante'],
        'maquinaria_sugerida': ['Mezcladora', 'Andamios'],
        'rendimiento_estimado': '8-12 m²/jornal cuadrilla',
        'desperdicio_estimado': '5%',
        'observaciones_tecnicas': 'Encadenado horizontal cada 2.5 m. Cantidad: ~24 ladrillos/m².',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'mamposteria_ladrillo_hueco_18',
        'rubro': 'Albañilería',
        'etapa': 'Mamposteria',
        'tarea': 'Mampostería ladrillo hueco 18 cm',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie neta restando vanos.',
        'palabras_clave_fuertes': ['ladrillo hueco 18', 'mamposteria 18', 'mamposteria de 18'],
        'palabras_clave_medias': [],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': ['demolicion'],
        'materiales_sugeridos': ['Ladrillo hueco 18', 'Cemento', 'Arena', 'Cal'],
        'mano_obra_sugerida': ['Oficial albañil', 'Ayudante'],
        'maquinaria_sugerida': ['Mezcladora', 'Andamios'],
        'rendimiento_estimado': '6-10 m²/jornal',
        'desperdicio_estimado': '5%',
        'observaciones_tecnicas': 'Espesor 18 cm. Cantidad: ~16 ladrillos/m².',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'mamposteria_ladrillo_comun',
        'rubro': 'Albañilería',
        'etapa': 'Mamposteria',
        'tarea': 'Mampostería ladrillo común',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²', 'm3'],
        'criterio_medicion': 'Superficie neta o m³ según espesor.',
        'palabras_clave_fuertes': ['ladrillo comun', 'ladrillo común', 'mamposteria de comun'],
        'palabras_clave_medias': ['ladrillo macizo'],
        'palabras_clave_debiles': ['ladrillo'],
        'palabras_excluyentes': ['hueco', 'demolicion'],
        'materiales_sugeridos': ['Ladrillo común', 'Cemento', 'Cal', 'Arena gruesa'],
        'mano_obra_sugerida': ['Oficial albañil', 'Ayudante'],
        'maquinaria_sugerida': ['Mezcladora', 'Andamios'],
        'rendimiento_estimado': '6-10 m²/jornal',
        'desperdicio_estimado': '8%',
        'observaciones_tecnicas': 'Cantidad típica: ~50 ladrillos/m² en cinta.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'tabique_durlock',
        'rubro': 'Albañilería',
        'etapa': 'Yeseria y Construccion en Seco',
        'tarea': 'Tabique de placa de yeso (Durlock)',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie de tabique terminado por ambas caras.',
        'palabras_clave_fuertes': ['tabique de durlock', 'durlock', 'placa de yeso', 'tabique seco', 'construccion en seco'],
        'palabras_clave_medias': ['placa', 'pladur'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Placa de yeso 12.5mm', 'Perfil montante', 'Perfil solera', 'Tornillos T2', 'Cinta de papel', 'Masilla'],
        'mano_obra_sugerida': ['Oficial montador', 'Ayudante'],
        'maquinaria_sugerida': ['Atornillador', 'Andamios'],
        'rendimiento_estimado': '15-25 m²/jornal',
        'desperdicio_estimado': '10%',
        'observaciones_tecnicas': 'Considerar relleno con lana de vidrio si requiere acústica.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 6. REVOQUES Y TERMINACIONES HUMEDAS
    # ============================================================
    {
        'id': 'revoque_grueso',
        'rubro': 'Revoques y Terminaciones',
        'etapa': 'Revoques',
        'tarea': 'Revoque grueso (jaharro)',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie revocada por cara, restando vanos > 1 m².',
        'palabras_clave_fuertes': ['revoque grueso', 'jaharro'],
        'palabras_clave_medias': ['revoque base'],
        'palabras_clave_debiles': ['revoque'],
        'palabras_excluyentes': ['fino', 'enlucido'],
        'materiales_sugeridos': ['Cemento', 'Cal', 'Arena gruesa'],
        'mano_obra_sugerida': ['Oficial revocador', 'Ayudante'],
        'maquinaria_sugerida': ['Mezcladora', 'Andamios'],
        'rendimiento_estimado': '15-25 m²/jornal cuadrilla',
        'desperdicio_estimado': '10%',
        'observaciones_tecnicas': 'Espesor promedio 1.5-2 cm.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'revoque_fino',
        'rubro': 'Revoques y Terminaciones',
        'etapa': 'Revoques',
        'tarea': 'Revoque fino / enlucido a la cal',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie revocada por cara.',
        'palabras_clave_fuertes': ['revoque fino', 'enlucido a la cal'],
        'palabras_clave_medias': ['fino', 'enlucido'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': ['grueso', 'jaharro'],
        'materiales_sugeridos': ['Cal hidratada', 'Cemento', 'Arena fina'],
        'mano_obra_sugerida': ['Oficial revocador', 'Ayudante'],
        'maquinaria_sugerida': ['Andamios'],
        'rendimiento_estimado': '20-30 m²/jornal',
        'desperdicio_estimado': '10%',
        'observaciones_tecnicas': 'Aplicar sobre grueso curado mínimo 7 días.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'azotado_hidrofugo',
        'rubro': 'Revoques y Terminaciones',
        'etapa': 'Revoques',
        'tarea': 'Azotado hidrófugo en muros',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie tratada.',
        'palabras_clave_fuertes': ['azotado hidrofugo', 'azotado hidrófugo'],
        'palabras_clave_medias': ['azotado', 'hidrofugo'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Cemento', 'Arena fina', 'Hidrófugo Sika 1', 'Agua'],
        'mano_obra_sugerida': ['Oficial', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '20 m²/jornal',
        'desperdicio_estimado': '10%',
        'observaciones_tecnicas': 'Solapar 10 cm en juntas verticales.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'contrapiso',
        'rubro': 'Revoques y Terminaciones',
        'etapa': 'Contrapisos y Carpetas',
        'tarea': 'Contrapiso de cascote / hormigón pobre',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²', 'm3'],
        'criterio_medicion': 'Superficie × espesor.',
        'palabras_clave_fuertes': ['contrapiso'],
        'palabras_clave_medias': [],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': ['carpeta'],
        'materiales_sugeridos': ['Cemento', 'Arena', 'Cascote', 'Cal'],
        'mano_obra_sugerida': ['Oficial', 'Ayudante'],
        'maquinaria_sugerida': ['Mezcladora'],
        'rendimiento_estimado': '30-50 m²/jornal según espesor',
        'desperdicio_estimado': '5%',
        'observaciones_tecnicas': 'Espesor típico 8-12 cm.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'carpeta_nivelacion',
        'rubro': 'Revoques y Terminaciones',
        'etapa': 'Contrapisos y Carpetas',
        'tarea': 'Carpeta de nivelación cementicia',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie nivelada.',
        'palabras_clave_fuertes': ['carpeta de nivelacion', 'carpeta cementicia'],
        'palabras_clave_medias': ['carpeta', 'nivelacion'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': ['contrapiso'],
        'materiales_sugeridos': ['Cemento', 'Arena fina', 'Aditivo nivelador'],
        'mano_obra_sugerida': ['Oficial', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '40-60 m²/jornal',
        'desperdicio_estimado': '8%',
        'observaciones_tecnicas': 'Espesor 2-3 cm, sobre contrapiso terminado.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 7. PISOS Y REVESTIMIENTOS
    # ============================================================
    {
        'id': 'piso_porcelanato',
        'rubro': 'Pisos y Revestimientos',
        'etapa': 'Pisos',
        'tarea': 'Colocación de porcelanato',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie colocada.',
        'palabras_clave_fuertes': ['porcelanato'],
        'palabras_clave_medias': [],
        'palabras_clave_debiles': ['piso'],
        'palabras_excluyentes': ['demolicion'],
        'materiales_sugeridos': ['Porcelanato', 'Pegamento cementicio', 'Pastina', 'Crucetas'],
        'mano_obra_sugerida': ['Oficial colocador', 'Ayudante'],
        'maquinaria_sugerida': ['Cortadora de cerámica'],
        'rendimiento_estimado': '10-15 m²/jornal',
        'desperdicio_estimado': '8%',
        'observaciones_tecnicas': 'Verificar niveles. Junta 2-3 mm.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'piso_ceramico',
        'rubro': 'Pisos y Revestimientos',
        'etapa': 'Pisos',
        'tarea': 'Colocación de cerámico',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie colocada.',
        'palabras_clave_fuertes': ['ceramico', 'ceramica'],
        'palabras_clave_medias': ['baldosa', 'mosaico'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': ['demolicion', 'porcelanato'],
        'materiales_sugeridos': ['Cerámico', 'Pegamento', 'Pastina'],
        'mano_obra_sugerida': ['Oficial colocador', 'Ayudante'],
        'maquinaria_sugerida': ['Cortadora cerámica'],
        'rendimiento_estimado': '12-18 m²/jornal',
        'desperdicio_estimado': '8%',
        'observaciones_tecnicas': 'Junta 3-5 mm.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'zocalo',
        'rubro': 'Pisos y Revestimientos',
        'etapa': 'Zocalos y Guardacantos',
        'tarea': 'Colocación de zócalo',
        'unidad_esperada': 'm',
        'unidades_validas': ['m', 'ml'],
        'criterio_medicion': 'Metro lineal contra muro.',
        'palabras_clave_fuertes': ['zocalo', 'zócalo'],
        'palabras_clave_medias': [],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Zócalo', 'Pegamento', 'Pastina'],
        'mano_obra_sugerida': ['Oficial', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '40-60 ml/jornal',
        'desperdicio_estimado': '5%',
        'observaciones_tecnicas': 'Cortes a 45° en esquinas.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'revestimiento_azulejo',
        'rubro': 'Pisos y Revestimientos',
        'etapa': 'Pisos',
        'tarea': 'Revestimiento cerámico de pared',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie revestida.',
        'palabras_clave_fuertes': ['revestimiento ceramico', 'azulejo', 'revestimiento de pared'],
        'palabras_clave_medias': ['revestimiento'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Azulejo', 'Pegamento', 'Pastina', 'Crucetas'],
        'mano_obra_sugerida': ['Oficial', 'Ayudante'],
        'maquinaria_sugerida': ['Cortadora'],
        'rendimiento_estimado': '8-12 m²/jornal',
        'desperdicio_estimado': '10%',
        'observaciones_tecnicas': 'Aplicar sobre superficie fina y plomada.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 8. CUBIERTAS E IMPERMEABILIZACION
    # ============================================================
    {
        'id': 'membrana_asfaltica',
        'rubro': 'Cubiertas e Impermeabilización',
        'etapa': 'Cubiertas y Techos',
        'tarea': 'Membrana asfáltica',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie aplicada con solapes 10 cm.',
        'palabras_clave_fuertes': ['membrana asfaltica', 'membrana asfáltica'],
        'palabras_clave_medias': ['membrana', 'impermeabilizacion'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Membrana asfáltica 4mm', 'Imprimación asfáltica'],
        'mano_obra_sugerida': ['Oficial impermeabilizador', 'Ayudante'],
        'maquinaria_sugerida': ['Soplete', 'Garrafa'],
        'rendimiento_estimado': '30-50 m²/jornal',
        'desperdicio_estimado': '12% por solapes',
        'observaciones_tecnicas': 'Solapar mínimo 10 cm. Subir 20 cm en muros.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'cubierta_chapa',
        'rubro': 'Cubiertas e Impermeabilización',
        'etapa': 'Cubiertas y Techos',
        'tarea': 'Cubierta de chapa galvanizada',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie cubierta.',
        'palabras_clave_fuertes': ['cubierta de chapa', 'techo de chapa', 'chapa galvanizada'],
        'palabras_clave_medias': ['chapa'],
        'palabras_clave_debiles': ['techo'],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Chapa galvanizada', 'Tornillos autoperforantes', 'Cumbrera', 'Gomas EPDM'],
        'mano_obra_sugerida': ['Oficial techista', 'Ayudante'],
        'maquinaria_sugerida': ['Atornillador'],
        'rendimiento_estimado': '40-60 m²/jornal',
        'desperdicio_estimado': '10%',
        'observaciones_tecnicas': 'Pendiente mínima 5%.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'aislacion_termica',
        'rubro': 'Cubiertas e Impermeabilización',
        'etapa': 'Aislaciones',
        'tarea': 'Aislación térmica con lana de vidrio / poliestireno',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie aislada.',
        'palabras_clave_fuertes': ['aislacion termica', 'lana de vidrio', 'poliestireno expandido'],
        'palabras_clave_medias': ['aislacion', 'aislante'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Lana de vidrio', 'Poliestireno expandido', 'Barrera vapor'],
        'mano_obra_sugerida': ['Oficial', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '40-80 m²/jornal',
        'desperdicio_estimado': '8%',
        'observaciones_tecnicas': 'Verificar coeficiente K según norma.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 9. INSTALACION ELECTRICA
    # ============================================================
    {
        'id': 'boca_electrica',
        'rubro': 'Instalación Eléctrica',
        'etapa': 'Instalaciones Electricas',
        'tarea': 'Boca eléctrica completa (caja + cañería + cable + tomacorriente)',
        'unidad_esperada': 'unidad',
        'unidades_validas': ['un', 'unidad', 'boca'],
        'criterio_medicion': 'Por boca terminada (incluye caño hasta tablero, cable, caja y artefacto).',
        'palabras_clave_fuertes': ['boca electrica', 'boca eléctrica', 'boca de tomacorriente', 'tomacorriente'],
        'palabras_clave_medias': ['boca', 'punto eléctrico'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Caño corrugado', 'Cable unipolar 2.5mm', 'Caja rectangular', 'Tomacorriente', 'Tornillos'],
        'mano_obra_sugerida': ['Oficial electricista', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '8-15 bocas/jornal',
        'desperdicio_estimado': '10%',
        'observaciones_tecnicas': 'Cumplir reglamentación AEA 90364.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'tablero_electrico',
        'rubro': 'Instalación Eléctrica',
        'etapa': 'Instalaciones Electricas',
        'tarea': 'Tablero seccional con disyuntor y térmicas',
        'unidad_esperada': 'unidad',
        'unidades_validas': ['un', 'unidad'],
        'criterio_medicion': 'Por tablero terminado y conectado.',
        'palabras_clave_fuertes': ['tablero electrico', 'tablero eléctrico', 'tablero seccional'],
        'palabras_clave_medias': ['tablero', 'tablero general'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Gabinete', 'Disyuntor', 'Térmica', 'Riel DIN', 'Borneras'],
        'mano_obra_sugerida': ['Electricista matriculado'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '1 tablero/jornal',
        'desperdicio_estimado': '5%',
        'observaciones_tecnicas': 'Requiere planos y memoria firmada.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'cableado_alimentacion',
        'rubro': 'Instalación Eléctrica',
        'etapa': 'Instalaciones Electricas',
        'tarea': 'Cableado de alimentación principal',
        'unidad_esperada': 'm',
        'unidades_validas': ['m', 'ml'],
        'criterio_medicion': 'Metro lineal de cable colocado.',
        'palabras_clave_fuertes': ['cableado de alimentacion', 'cable de alimentacion'],
        'palabras_clave_medias': ['cable unipolar', 'cableado'],
        'palabras_clave_debiles': ['cable'],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Cable unipolar 4mm', 'Cable unipolar 6mm', 'Caño rígido'],
        'mano_obra_sugerida': ['Electricista', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '50-80 m/jornal',
        'desperdicio_estimado': '10%',
        'observaciones_tecnicas': 'Verificar sección según consumo.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 10. INSTALACION SANITARIA
    # ============================================================
    {
        'id': 'cañeria_agua_fria',
        'rubro': 'Instalación Sanitaria',
        'etapa': 'Instalaciones Sanitarias',
        'tarea': 'Cañería de agua fría PPR',
        'unidad_esperada': 'm',
        'unidades_validas': ['m', 'ml'],
        'criterio_medicion': 'Metro lineal de cañería.',
        'palabras_clave_fuertes': ['cañeria de agua fria', 'cañería de agua fría', 'agua fria ppr'],
        'palabras_clave_medias': ['agua fria', 'agua fría', 'ppr'],
        'palabras_clave_debiles': ['agua'],
        'palabras_excluyentes': ['caliente', 'cloaca'],
        'materiales_sugeridos': ['Caño PPR 20mm', 'Codos', 'Tee', 'Llaves de paso'],
        'mano_obra_sugerida': ['Plomero', 'Ayudante'],
        'maquinaria_sugerida': ['Termofusora'],
        'rendimiento_estimado': '20-40 m/jornal',
        'desperdicio_estimado': '10%',
        'observaciones_tecnicas': 'Prueba hidráulica a 8 atm antes de cerrar canaletas.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'desague_cloacal',
        'rubro': 'Instalación Sanitaria',
        'etapa': 'Instalaciones Sanitarias',
        'tarea': 'Desagüe cloacal PVC',
        'unidad_esperada': 'm',
        'unidades_validas': ['m', 'ml'],
        'criterio_medicion': 'Metro lineal por diámetro.',
        'palabras_clave_fuertes': ['desague cloacal', 'desagüe cloacal', 'cloaca pvc', 'caño cloacal'],
        'palabras_clave_medias': ['cloaca', 'desague', 'desagüe'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': ['pluvial', 'agua fria'],
        'materiales_sugeridos': ['Caño PVC 110mm', 'Caño PVC 60mm', 'Codos', 'Ramales'],
        'mano_obra_sugerida': ['Plomero', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '20-30 m/jornal',
        'desperdicio_estimado': '8%',
        'observaciones_tecnicas': 'Pendiente 1-2% mínima. Cámaras cada 15 m.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'artefacto_sanitario',
        'rubro': 'Instalación Sanitaria',
        'etapa': 'Instalaciones Sanitarias',
        'tarea': 'Provisión y colocación de artefacto sanitario',
        'unidad_esperada': 'unidad',
        'unidades_validas': ['un', 'unidad'],
        'criterio_medicion': 'Por artefacto.',
        'palabras_clave_fuertes': ['inodoro', 'lavatorio', 'bidet', 'pileta cocina', 'artefacto sanitario'],
        'palabras_clave_medias': ['sanitario'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Inodoro', 'Mochila', 'Anillo de cera', 'Tornillería', 'Sellador'],
        'mano_obra_sugerida': ['Plomero', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '3-5 artefactos/jornal',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Incluye griferías si vienen separadas.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 11. INSTALACION DE GAS
    # ============================================================
    {
        'id': 'cañeria_gas',
        'rubro': 'Instalación de Gas',
        'etapa': 'Instalaciones de Gas',
        'tarea': 'Cañería de gas (epoxi o cobre)',
        'unidad_esperada': 'm',
        'unidades_validas': ['m', 'ml'],
        'criterio_medicion': 'Metro lineal por diámetro.',
        'palabras_clave_fuertes': ['cañeria de gas', 'cañería de gas', 'caño de gas'],
        'palabras_clave_medias': ['gas natural', 'instalacion de gas'],
        'palabras_clave_debiles': ['gas'],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Caño epoxi', 'Codo de gas', 'Llave de paso de gas', 'Sellador específico'],
        'mano_obra_sugerida': ['Gasista matriculado', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '15-25 m/jornal',
        'desperdicio_estimado': '8%',
        'observaciones_tecnicas': 'Prueba de hermeticidad obligatoria. Plano firmado por matriculado.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'gabinete_gas',
        'rubro': 'Instalación de Gas',
        'etapa': 'Instalaciones de Gas',
        'tarea': 'Gabinete reglamentario de gas',
        'unidad_esperada': 'unidad',
        'unidades_validas': ['un', 'unidad'],
        'criterio_medicion': 'Por gabinete.',
        'palabras_clave_fuertes': ['gabinete de gas', 'nicho de gas'],
        'palabras_clave_medias': ['gabinete'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Gabinete chapa', 'Cerradura', 'Tornillería'],
        'mano_obra_sugerida': ['Gasista', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '1/jornal',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Verificar dimensiones según ENARGAS.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 12. CARPINTERIAS
    # ============================================================
    {
        'id': 'puerta_interior',
        'rubro': 'Carpinterías',
        'etapa': 'Carpinterias',
        'tarea': 'Puerta interior de placa (hoja + marco)',
        'unidad_esperada': 'unidad',
        'unidades_validas': ['un', 'unidad'],
        'criterio_medicion': 'Por puerta colocada.',
        'palabras_clave_fuertes': ['puerta interior', 'puerta de placa', 'puerta placa'],
        'palabras_clave_medias': ['puerta'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': ['ventana', 'porton', 'exterior'],
        'materiales_sugeridos': ['Hoja placa', 'Marco metálico/madera', 'Bisagras', 'Cerradura', 'Pomo'],
        'mano_obra_sugerida': ['Oficial carpintero', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '2-3 puertas/jornal',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Verificar luces de plomada.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'ventana_aluminio',
        'rubro': 'Carpinterías',
        'etapa': 'Carpinterias',
        'tarea': 'Ventana de aluminio con DVH',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²', 'unidad'],
        'criterio_medicion': 'Superficie de abertura o por unidad.',
        'palabras_clave_fuertes': ['ventana de aluminio', 'ventana dvh', 'ventana aluminio'],
        'palabras_clave_medias': ['ventana'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': ['puerta'],
        'materiales_sugeridos': ['Perfil aluminio', 'DVH', 'Selladores', 'Burletes', 'Tornillería'],
        'mano_obra_sugerida': ['Oficial aluminiero', 'Ayudante'],
        'maquinaria_sugerida': ['Atornillador'],
        'rendimiento_estimado': '4-6 m²/jornal',
        'desperdicio_estimado': '5%',
        'observaciones_tecnicas': 'Sellar perimetralmente con silicona neutra.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'porton_garage',
        'rubro': 'Carpinterías',
        'etapa': 'Herreria y Aberturas Metalicas',
        'tarea': 'Portón de garage levadizo',
        'unidad_esperada': 'unidad',
        'unidades_validas': ['un', 'unidad', 'm2'],
        'criterio_medicion': 'Por portón colocado.',
        'palabras_clave_fuertes': ['porton levadizo', 'portón levadizo', 'porton de garage'],
        'palabras_clave_medias': ['porton', 'portón'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': ['ventana'],
        'materiales_sugeridos': ['Portón levadizo', 'Motor', 'Riel', 'Tornillería', 'Tablero'],
        'mano_obra_sugerida': ['Herrero', 'Electricista'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '1 portón/jornal',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Incluye motorización si corresponde.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 13. PINTURA
    # ============================================================
    {
        'id': 'pintura_latex_interior',
        'rubro': 'Pintura',
        'etapa': 'Pintura',
        'tarea': 'Pintura látex interior (3 manos)',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie pintada.',
        'palabras_clave_fuertes': ['pintura latex interior', 'pintura latex', 'latex interior'],
        'palabras_clave_medias': ['pintura interior', 'pintura latex', 'latex'],
        'palabras_clave_debiles': ['pintura'],
        'palabras_excluyentes': ['exterior', 'esmalte', 'antioxido'],
        'materiales_sugeridos': ['Pintura látex', 'Imprimación fijadora', 'Enduido plástico', 'Lijas', 'Cinta de papel'],
        'mano_obra_sugerida': ['Oficial pintor', 'Ayudante'],
        'maquinaria_sugerida': ['Rodillo', 'Pincel', 'Bandeja'],
        'rendimiento_estimado': '40-60 m²/jornal',
        'desperdicio_estimado': '10%',
        'observaciones_tecnicas': '3 manos: 1 fijador + 2 latex. Lijar entre manos.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'pintura_exterior',
        'rubro': 'Pintura',
        'etapa': 'Pintura',
        'tarea': 'Pintura exterior frentes (látex acrílico)',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie pintada.',
        'palabras_clave_fuertes': ['pintura exterior', 'pintura latex acrilico', 'frente'],
        'palabras_clave_medias': ['acrilico', 'acrílico'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': ['interior'],
        'materiales_sugeridos': ['Látex acrílico exterior', 'Sellador acrílico', 'Reparador'],
        'mano_obra_sugerida': ['Oficial pintor', 'Ayudante'],
        'maquinaria_sugerida': ['Andamios', 'Rodillo'],
        'rendimiento_estimado': '30-50 m²/jornal',
        'desperdicio_estimado': '12%',
        'observaciones_tecnicas': 'Aplicar con humedad < 60% y temp > 10°C.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'esmalte_sintetico',
        'rubro': 'Pintura',
        'etapa': 'Pintura',
        'tarea': 'Esmalte sintético sobre herrería',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²'],
        'criterio_medicion': 'Superficie pintada.',
        'palabras_clave_fuertes': ['esmalte sintetico', 'esmalte sintético', 'pintura herreria', 'antioxido'],
        'palabras_clave_medias': ['esmalte', 'antióxido'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': ['latex'],
        'materiales_sugeridos': ['Esmalte sintético', 'Antióxido', 'Aguarrás', 'Lijas'],
        'mano_obra_sugerida': ['Oficial pintor', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '15-25 m²/jornal',
        'desperdicio_estimado': '10%',
        'observaciones_tecnicas': 'Preparar con antióxido convertidor.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 14. EQUIPOS Y MAQUINARIA (alquileres frecuentes)
    # ============================================================
    {
        'id': 'alquiler_andamio',
        'rubro': 'Equipos y Maquinaria',
        'etapa': 'Equipos y Maquinaria',
        'tarea': 'Alquiler de andamio tubular',
        'unidad_esperada': 'mes',
        'unidades_validas': ['mes', 'meses', 'm2'],
        'criterio_medicion': 'Por mes de alquiler o m² × mes.',
        'palabras_clave_fuertes': ['alquiler de andamio', 'andamio tubular', 'alquiler andamio'],
        'palabras_clave_medias': ['andamio'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': [],
        'mano_obra_sugerida': ['Armador de andamios'],
        'maquinaria_sugerida': ['Andamio tubular'],
        'rendimiento_estimado': 'Según tiempo de obra',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Considerar montaje y desmontaje.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'volquete',
        'rubro': 'Equipos y Maquinaria',
        'etapa': 'Equipos y Maquinaria',
        'tarea': 'Volquete para retiro de escombros',
        'unidad_esperada': 'unidad',
        'unidades_validas': ['un', 'unidad', 'viaje'],
        'criterio_medicion': 'Por volquete completo.',
        'palabras_clave_fuertes': ['volquete', 'retiro escombro', 'retiro de escombro'],
        'palabras_clave_medias': ['escombro', 'contenedor'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': [],
        'mano_obra_sugerida': [],
        'maquinaria_sugerida': ['Volquete 6m³'],
        'rendimiento_estimado': '1 volquete = 6 m³',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Permiso municipal puede ser requerido.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 14b. DEMOLICIONES (rubro implícito en preliminares + casos puntuales)
    # ============================================================
    {
        'id': 'demolicion_muro',
        'rubro': 'Movimiento de Suelos',
        'etapa': 'Demoliciones',
        'tarea': 'Demolición de muro / mampostería existente',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²', 'm3'],
        'criterio_medicion': 'Superficie o volumen demolido.',
        'palabras_clave_fuertes': ['demolicion de muro', 'demolición de muro', 'demolicion de mamposteria', 'rotura de muro'],
        'palabras_clave_medias': ['demolicion', 'demolición', 'rotura', 'picado'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': ['Volquete (alquiler)', 'Bolsas de escombros'],
        'mano_obra_sugerida': ['Oficial', 'Ayudante'],
        'maquinaria_sugerida': ['Martillo demoledor', 'Volquete'],
        'rendimiento_estimado': '15-25 m²/jornal según muro',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Verificar si afecta estructura. Apuntalar antes si aplica.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 14c. MANO DE OBRA (cuando aparece como item suelto)
    # ============================================================
    {
        'id': 'cuadrilla_albanil',
        'rubro': 'Albañilería',
        'etapa': 'Mamposteria',
        'tarea': 'Cuadrilla de albañilería (oficial + ayudante)',
        'unidad_esperada': 'jornal',
        'unidades_validas': ['jornal', 'jornales', 'dia', 'dias', 'h'],
        'criterio_medicion': 'Por jornal de cuadrilla.',
        'palabras_clave_fuertes': ['cuadrilla albanil', 'cuadrilla de albañileria', 'oficial albanil'],
        'palabras_clave_medias': ['albanil', 'albañil', 'cuadrilla'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': [],
        'mano_obra_sugerida': ['Oficial albañil', 'Ayudante'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '1 cuadrilla = 1 oficial + 1 ayudante',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Cargar cargas sociales sobre el jornal básico.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'oficial_especializado_mo',
        'rubro': 'Albañilería',
        'etapa': 'Mamposteria',
        'tarea': 'Mano de obra oficial especializado',
        'unidad_esperada': 'jornal',
        'unidades_validas': ['jornal', 'jornales', 'dia', 'h'],
        'criterio_medicion': 'Por jornal trabajado.',
        'palabras_clave_fuertes': ['oficial especializado', 'oficial calificado'],
        'palabras_clave_medias': ['oficial'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': ['ayudante', 'medio'],
        'materiales_sugeridos': [],
        'mano_obra_sugerida': ['Oficial especializado'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': 'Según tarea',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Categoría UOCRA.',
        'fuente': 'criterio interno OBYRA',
    },

    # ============================================================
    # 15. LIMPIEZA Y ENTREGA FINAL
    # ============================================================
    {
        'id': 'limpieza_final',
        'rubro': 'Limpieza y Entrega Final',
        'etapa': 'Limpieza Final y Entrega',
        'tarea': 'Limpieza final de obra',
        'unidad_esperada': 'm2',
        'unidades_validas': ['m2', 'm²', 'gl'],
        'criterio_medicion': 'Superficie limpiada o global.',
        'palabras_clave_fuertes': ['limpieza final', 'limpieza de obra final', 'entrega final'],
        'palabras_clave_medias': ['limpieza fina'],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': ['inicial'],
        'materiales_sugeridos': ['Detergente', 'Lavandina', 'Productos limpieza', 'Bolsas residuos'],
        'mano_obra_sugerida': ['Personal limpieza'],
        'maquinaria_sugerida': ['Hidrolavadora'],
        'rendimiento_estimado': '50-80 m²/jornal',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Antes de entrega al cliente.',
        'fuente': 'criterio interno OBYRA',
    },
    {
        'id': 'pruebas_finales',
        'rubro': 'Limpieza y Entrega Final',
        'etapa': 'Limpieza Final y Entrega',
        'tarea': 'Pruebas finales y puesta en marcha',
        'unidad_esperada': 'gl',
        'unidades_validas': ['gl', 'global'],
        'criterio_medicion': 'Global.',
        'palabras_clave_fuertes': ['pruebas finales', 'puesta en marcha', 'habilitacion'],
        'palabras_clave_medias': [],
        'palabras_clave_debiles': [],
        'palabras_excluyentes': [],
        'materiales_sugeridos': [],
        'mano_obra_sugerida': ['Jefe de obra', 'Especialistas'],
        'maquinaria_sugerida': [],
        'rendimiento_estimado': '2-5 jornales',
        'desperdicio_estimado': '0%',
        'observaciones_tecnicas': 'Probar instalaciones, llaves, artefactos.',
        'fuente': 'criterio interno OBYRA',
    },
]


def reglas_por_rubro(rubro: str) -> list:
    """Devuelve las reglas que pertenecen a un rubro dado."""
    return [r for r in REGLAS_TECNICAS if r.get('rubro') == rubro]


def regla_por_id(regla_id: str) -> dict | None:
    """Busca una regla por su id."""
    for r in REGLAS_TECNICAS:
        if r.get('id') == regla_id:
            return r
    return None


def total_reglas() -> int:
    return len(REGLAS_TECNICAS)
