name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  migrate:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: migrator
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: obyra_ci
        options: >-
          --health-cmd "pg_isready -U migrator -d obyra_ci"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    env:
      FLASK_APP: wsgi.py
      DATABASE_URL: postgresql+psycopg://migrator:postgres@localhost:5432/obyra_ci
      DB_SSLMODE: disable
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: flask db upgrade
